services:
  - type: web
    name: vanilla-todo-backend
    env: node
    buildCommand: cd VB && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        fromDatabase:
          name: vanilla-todo-db
          property: connectionString

  - type: web
    name: vanilla-todo-frontend
    env: static
    buildCommand: |
      echo 'Frontend will be served from the VF directory'
    staticPublishPath: ./VF
    envVars:
      - key: API_URL
        value: https://vanilla-todo-backend.onrender.com

databases:
  - name: vanilla-todo-db
    databaseName: todos
    user: vanilla_user
